version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${DOCKER_USER_ID}/flask
  production:
    image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
    command: python3 app.py
    volumes:
      - .:/code
    ports:
      - "80:80"

